config/routes.rb
Rails.application.routes.draw do
  root 'facts#random'

  resources :facts do
    resources :citations, only: :create
  end
  get 'all', to: 'facts#all'
  get 'random', to: 'facts#random'

end

app/models/citation.rb
class Citation < ActiveRecord::Base
  validates :source, presence: true, length: { minimum: 5 }
  belongs_to :fact
end

app/models/fact.rb
class Fact < ActiveRecord::Base
  validates :text, presence: true, length: { minimum: 10 }
  has_many :citations

  def self.search(search)
    where("text ILIKE ? OR initial_citation ILIKE ?", "%#{search}%", "%#{search}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/citations_controller.rb
class CitationsController < ApplicationController

  def create
    @fact = Fact.find(params[:fact_id])
    @citation = @fact.citations.new(citation_params)
    if @citation.invalid?
      flash[:error] = 'Please enter a valid citation longer than 5 characters.'
      redirect_to root_path
    else
      @citation.save
      redirect_to root_path
      flash[:success] = 'Thanks for adding a citation!'
    end
  end

  private

  def citation_params
    params.require(:citation).permit(:source)
  end

end

app/controllers/facts_controller.rb
class FactsController < ApplicationController
  def index
    if params[:search]
      @facts = Fact.search(params[:search]).order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
    else
      @facts = Fact.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
    end
  end

  def random
    @fact = Fact.order("RANDOM()").first
    @citation = Citation.new
  end

  def all
    @facts = Fact.paginate(:page => params[:page], :per_page => 10)
  end

  def create
    @fact = Fact.new(fact_params)
    if @fact.invalid?
      flash[:error] = 'Please enter a valid fact longer than 10 characters.'
      redirect_to root_path
    else
      @fact.flags = 0
      @fact.save
      redirect_to root_path
      flash[:success] = 'Thanks for adding a fact!'
    end
  end

  def show
    @fact = Fact.find(params[:id])
    @citation = Citation.new
  end

  def update
    Fact.find(params[:id]).update_attributes(fact_params)
  end

  private

  def fact_params
    params.require(:fact).permit(:text, :initial_citation, :flags)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/citations_helper.rb
module CitationsHelper
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/views/facts/all.html.erb
<% @facts.each do |fact| %>

<div class="fact-box">

<h1><%= fact.text %></h1>

<div class="text-right">
<% if fact.flags.to_i > 0 %>
<p class="text-center"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> This fact has been flagged as false <b><% if fact.flags == 1 %> 1 time. <% else %> <%= fact.flags %> times. <% end %></b> </p>
<% end %>
<%= link_to 'Go to Fact', fact_path(fact), class: 'btn-nav' %>
</div>
<br/>

</div>
<br/>

<% end %>

<div class="apple_pagination text-center">
<%= will_paginate @facts %>
</div>

app/views/facts/index.html.erb
<% if @facts.length == 0 %>

<div class="fact-box text-center">Sorry, no facts matched your query. Please try searching for something else.</div>

<% else %>

<% @facts.each do |fact| %>

<div class="fact-box">

<h1><%= fact.text %></h1>

<div class="text-right">
<% if fact.flags.to_i > 0 %>
<p class="text-center"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> This fact has been flagged as false <b><% if fact.flags == 1 %> 1 time. <% else %> <%= fact.flags %> times. <% end %></b> </p>
<% end %>
<%= link_to 'Go to Fact', fact_path(fact), class: 'btn-nav' %>
</div>
<br/>

</div>
<br/>

<% end %>

<% if @facts.length > 10 %>
<div class="apple_pagination text-center">
  <%= will_paginate @facts %>
</div>
<% end %>

<% end %>

app/views/facts/random.html.erb
<script>
$(function() {
  $(".btn-false").click(function() {
    var confirmed = confirm("You are about to flag this fact as false. You cannot undo this action. Are you sure you wish to proceed?");
    if (confirmed === true) {
      var updateURL = $(event.target).data("update-url");
      var currentFlags = $(event.target).data("current-flags");
      var newFlags = currentFlags + 1;
      $.ajax({
        type: 'PUT',
        url: updateURL,
        dataType: 'json',
        data: { fact: { flags: newFlags }}
      });
      location.reload();
    }
  });
});
</script>

<div class="fact-box">

<h1 class="text-center"><%= @fact.text %></h1>

<div class="pull-right text-right">
<% if @fact.flags.to_i > 0 %>
<p class="text-center"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> This fact has been flagged as false <b><% if @fact.flags == 1 %> 1 time. <% else %> <%= @fact.flags %> times. <% end %></b> </p>
<% end %>

<button class="btn-false" data-update-url="<%= fact_path(@fact) %>" data-current-flags="<%= @fact.flags %>"><i class="fa fa-flag" aria-hidden="true"></i> False</button>
</div>

<br class="clear"/>

<div class="text-center">
<%= link_to 'Next Fact!', root_path, class: 'btn-nav text-center' %>
</div>

<div class="citations">
<h2>Citations</h2>

<% if @fact.initial_citation.present? %>
<p><%= @fact.initial_citation %></p>
<% end %>

<% if @fact.citations.present? %>
<% @fact.citations.each do |citation| %>
<p><%= citation.source %></p>
<% end %>
<% end %>

<% if !@fact.initial_citation.present? && !@fact.citations.present? %>
<p>This fact has not been cited. Be the first to add a citation!</p>
<% end %>

<p><!-- Button trigger modal -->
<%= link_to 'Add Citation', '#', class: 'btn-citation', data: {toggle: 'modal', target: '#addCitation'} %></p>
</div>

</div>

<!-- New citation modal -->
  <div class="modal fade" id="addCitation" tabindex="-1" role="dialog" aria-labelledby="addCitationLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h2>Add a citation</h2>
        </div>
        <div class="modal-body">
          <div class="form">
            <%= simple_form_for @citation, url: fact_citations_path(@fact) do |f| %>
              <%= f.input :source, label: "Citation" %>
              <i>Add a primary source citation. Optional: Quote the original Latin/Greek source and translate it. You can also use this space to refute a fact.</i>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-submit" data-dismiss="modal">Close</button>
          <%= f.submit 'Submit', class: 'btn btn-success' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/facts/show.html.erb
<script>
$(function() {
  $(".btn-false").click(function() {
    var confirmed = confirm("You are about to flag this fact as false. You cannot undo this action. Are you sure you wish to proceed?");
    if (confirmed === true) {
      var updateURL = $(event.target).data("update-url");
      var currentFlags = $(event.target).data("current-flags");
      var newFlags = currentFlags + 1;
      $.ajax({
        type: 'PUT',
        url: updateURL,
        dataType: 'json',
        data: { fact: { flags: newFlags }}
      });
      location.reload();
    }
  });
});
</script>

<div class="fact-box">

<h1 class="text-center"><%= @fact.text %></h1>

<div class="pull-right text-right">
<% if @fact.flags.to_i > 0 %>
<p class="text-center"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> This fact has been flagged as false <b><% if @fact.flags == 1 %> 1 time. <% else %> <%= @fact.flags %> times. <% end %></b> </p>
<% end %>

<button class="btn-false" data-update-url="<%= fact_path(@fact) %>" data-current-flags="<%= @fact.flags %>"><i class="fa fa-flag" aria-hidden="true"></i> False</button>
</div>

<br class="clear"/>

<div class="citations">
<h2>Citations</h2>

<% if @fact.initial_citation.present? %>
<p><%= @fact.initial_citation %></p>
<% end %>

<% if @fact.citations.present? %>
<% @fact.citations.each do |citation| %>
<p><%= citation.source %></p>
<% end %>
<% end %>

<% if !@fact.initial_citation.present? && !@fact.citations.present? %>
<p>This fact has not been cited. Be the first to add a citation!</p>
<% end %>

<p><!-- Button trigger modal -->
<%= link_to 'Add Citation', '#', class: 'btn-citation', data: {toggle: 'modal', target: '#addCitation'} %></p>
</div>

</div>

<!-- New citation modal -->
  <div class="modal fade" id="addCitation" tabindex="-1" role="dialog" aria-labelledby="addCitationLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h2>Add a citation</h2>
        </div>
        <div class="modal-body">
          <div class="form">
            <%= simple_form_for @citation, url: fact_citations_path(@fact) do |f| %>
              <%= f.input :source, label: "Citation" %>
              <i>Add a primary source citation. Optional: Quote the original Latin/Greek source and translate it. You can also use this space to refute a fact.</i>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-submit" data-dismiss="modal">Close</button>
          <%= f.submit 'Submit', class: 'btn btn-success' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FACTA | Fun Facts about Ancient Rome</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://use.fontawesome.com/ee14bb1f23.js"></script>
</head>
<body>
<div id="wrap">
<div class="navbar">
<%= link_to 'FACTA', root_path %> <span class="disappear white">// <span class="text-muted">Fun Facts About Ancient Rome</span></span>
</div>

 <% if flash[:error].present? %>
      <div class="alert alert-danger">
        <%= flash[:error] %>
      </div>
      <br/>
<% end %>
 <% if flash[:success].present? %>
      <div class="alert alert-success">
        <%= flash[:success] %>
      </div>
      <br/>
<% end %>

<br/><br/>
<div class="text-center">
<%= link_to 'All Facts', all_path, class: 'btn-nav' %>
<!-- Button trigger modal -->
<%= link_to 'Add Fact', '#', class: 'btn-nav', data: {toggle: 'modal', target: '#addFact'} %>
<br/><br/>
<%= form_tag(facts_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "e.g. gladiators", class: 'search-input' %>
  <%= submit_tag "Search", :name => nil, class: 'btn btn-info' %>
<% end %>
</div>
<br/><br/>

<%= yield %>

<!-- New fact modal -->
  <div class="modal fade" id="addFact" tabindex="-1" role="dialog" aria-labelledby="addFactLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h2>Add a fact</h2>
        </div>
        <div class="modal-body">
          <div class="form">
            <%= simple_form_for Fact.new do |f| %>
              <%= f.input :text, label: "Fact" %>
              <br>
              <%= f.input :initial_citation, label: "Citation" %>
              <i>Optional: Add a primary source citation. Super optional: Quote the original Latin/Greek source and translate it.</i>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-submit" data-dismiss="modal">Close</button>
          <%= f.submit 'Submit', class: 'btn btn-info' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

</div>
<div id="footer">
<div class="container">
      Made by <a href="http://www.kellylougheed.com" target="_blank">Kelly Lougheed</a>. <a href="mailto:hello@kellylougheed.com?Subject=Hello"><i class="fa fa-envelope-o" aria-hidden="true"></i></a> <a href="https://www.linkedin.com/in/kelly-lougheed-ba147b121" target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i></a> <a href="https://github.com/kellylougheed" target="_blank"><i class="fa fa-github" aria-hidden="true"></i></a> <a href="http://www.twitter.com/kellylougheed" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a>
  </div>
  </div>

</body>
</html>